baseURL = 'https://kucukaslan.com.tr/'
languageCode = 'tr-tr'
title = 'Muhammed Can Küçükaslan'

publishDir="docs"
theme = 'lugo'


[params]
  author = "Muhammed Can Küçükaslan"
  og_image = "/img/knuth_taocp.png"

[markup.goldmark.renderer]
unsafe= true

[[menu.main]]
weight = 1
name = "Home"
url = "/"

[[menu.main]]
weight = 2
name = "About"
url = "/about/"
